#!/bin/bash

# Program for a to-do list, 1st step, this one is for adding tasks

title="To-Do List"
tasks="To-Do"
date="$(date +"%x %r ")"
file="/home/guillermo/bin/todolist.txt"
cal="execute cal -3"

echo "                            $tasks                                    "

echo " -------------------------------------------------------------------- "
         
echo "$(cal -3) "  

echo " -------------------------------------------------------------------- "          
          
echo "                  Please input your new task"
     
read  newinput 

echo $date $newinput  >> $file
