#!/bin/bash

# Program for a to-do list, 3rd step, this one is for deleting tasks

title="To-Do List"
tasks="To-Do"
date="$(date +"%x %r ")"
file="/home/guillermo/bin/todolist.txt"

echo "                     $title
                    The  Deleter"
                    
echo " -------------------------------------------------------- "                    
                    
cat -b $file

echo " -------------------------------------------------------- "

echo "                     Delete a task? 
                         y or n"

read insert

if [ "$insert" = "y" ]
then
    echo "                       what line?"
else
    exit 
fi

read numberin

sed -i "$numberin"'d' $file
