#!/bin/bash

# Program for a to-do list, 4th step, this one is for striking through completed tasks

title="To-Do List"
tasks="To-Do"
date="$(date +"%x %r ")"
file="/home/guillermo/bin/todolist.txt"

echo "                     $title"

echo " ------------------------------------------------------ "

cat -b $file

echo " ------------------------------------------------------ "

echo "       Select line of task you wish to complete"

read input

sed "$input"'d' s/"$input"'d'/echo -e "\e[9m"$input"'d'\e[0m"/ >> $file
